/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace YieldRouter {
  export type ReputationSnapshotStruct = {
    timestamp: BigNumberish;
    score: BigNumberish;
    tier: BigNumberish;
  };

  export type ReputationSnapshotStructOutput = [
    timestamp: bigint,
    score: bigint,
    tier: bigint
  ] & { timestamp: bigint; score: bigint; tier: bigint };
}

export declare namespace IMorpho {
  export type MarketParamsStruct = {
    loanToken: AddressLike;
    collateralToken: AddressLike;
    oracle: AddressLike;
    irm: AddressLike;
    lltv: BigNumberish;
  };

  export type MarketParamsStructOutput = [
    loanToken: string,
    collateralToken: string,
    oracle: string,
    irm: string,
    lltv: bigint
  ] & {
    loanToken: string;
    collateralToken: string;
    oracle: string;
    irm: string;
    lltv: bigint;
  };
}

export interface YieldRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bronzeThreshold"
      | "deposit"
      | "depositToVenue"
      | "deposits"
      | "fxrp"
      | "getBestVenue"
      | "getCurrentAPY"
      | "getReputationHistory"
      | "getReputationTier"
      | "goldThreshold"
      | "kinetic"
      | "kineticMockAPY"
      | "morpho"
      | "morphoMarketParams"
      | "morphoMockAPY"
      | "owner"
      | "rebalance"
      | "renounceOwnership"
      | "reputationHistory"
      | "setMockAPY"
      | "setMorphoMarketParams"
      | "setThresholds"
      | "silverThreshold"
      | "transferOwnership"
      | "userUsingMorpho"
      | "userVenue"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "MockAPYUpdated"
      | "MorphoMarketParamsUpdated"
      | "OwnershipTransferred"
      | "Rebalanced"
      | "ReputationSnapshotUpdated"
      | "RoutingUpdated"
      | "ThresholdsUpdated"
      | "UserRoutingUpdated"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bronzeThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToVenue",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "fxrp", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBestVenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentAPY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReputationHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReputationTier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "goldThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "kinetic", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "kineticMockAPY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "morpho", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "morphoMarketParams",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "morphoMockAPY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "rebalance", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputationHistory",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMockAPY",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMorphoMarketParams",
    values: [IMorpho.MarketParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setThresholds",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "silverThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userUsingMorpho",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userVenue",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "bronzeThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositToVenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposits", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fxrp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBestVenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentAPY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputationHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputationTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "goldThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "kinetic", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "kineticMockAPY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "morpho", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "morphoMarketParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "morphoMockAPY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rebalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setMockAPY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMorphoMarketParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "silverThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userUsingMorpho",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userVenue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    newTotal: BigNumberish,
    venue: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    newTotal: bigint,
    venue: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    newTotal: bigint;
    venue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MockAPYUpdatedEvent {
  export type InputTuple = [venue: BigNumberish, newAPY: BigNumberish];
  export type OutputTuple = [venue: bigint, newAPY: bigint];
  export interface OutputObject {
    venue: bigint;
    newAPY: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MorphoMarketParamsUpdatedEvent {
  export type InputTuple = [
    loanToken: AddressLike,
    collateralToken: AddressLike,
    oracle: AddressLike,
    irm: AddressLike,
    lltv: BigNumberish
  ];
  export type OutputTuple = [
    loanToken: string,
    collateralToken: string,
    oracle: string,
    irm: string,
    lltv: bigint
  ];
  export interface OutputObject {
    loanToken: string;
    collateralToken: string;
    oracle: string;
    irm: string;
    lltv: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RebalancedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    fromVenue: BigNumberish,
    toVenue: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    fromVenue: bigint,
    toVenue: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    fromVenue: bigint;
    toVenue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationSnapshotUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    timestamp: BigNumberish,
    score: BigNumberish,
    tier: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    timestamp: bigint,
    score: bigint,
    tier: bigint
  ];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
    score: bigint;
    tier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoutingUpdatedEvent {
  export type InputTuple = [morpho: AddressLike, useMorpho: boolean];
  export type OutputTuple = [morpho: string, useMorpho: boolean];
  export interface OutputObject {
    morpho: string;
    useMorpho: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdsUpdatedEvent {
  export type InputTuple = [
    newBronzeThreshold: BigNumberish,
    newSilverThreshold: BigNumberish,
    newGoldThreshold: BigNumberish
  ];
  export type OutputTuple = [
    newBronzeThreshold: bigint,
    newSilverThreshold: bigint,
    newGoldThreshold: bigint
  ];
  export interface OutputObject {
    newBronzeThreshold: bigint;
    newSilverThreshold: bigint;
    newGoldThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRoutingUpdatedEvent {
  export type InputTuple = [user: AddressLike, preference: BigNumberish];
  export type OutputTuple = [user: string, preference: bigint];
  export interface OutputObject {
    user: string;
    preference: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    remaining: BigNumberish,
    venue: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    remaining: bigint,
    venue: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    remaining: bigint;
    venue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface YieldRouter extends BaseContract {
  connect(runner?: ContractRunner | null): YieldRouter;
  waitForDeployment(): Promise<this>;

  interface: YieldRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bronzeThreshold: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  depositToVenue: TypedContractMethod<
    [amount: BigNumberish, venue: BigNumberish],
    [void],
    "nonpayable"
  >;

  deposits: TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { amount: bigint; timestamp: bigint }],
    "view"
  >;

  fxrp: TypedContractMethod<[], [string], "view">;

  getBestVenue: TypedContractMethod<[], [bigint], "view">;

  getCurrentAPY: TypedContractMethod<[], [bigint], "view">;

  getReputationHistory: TypedContractMethod<
    [user: AddressLike],
    [YieldRouter.ReputationSnapshotStructOutput[]],
    "view"
  >;

  getReputationTier: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  goldThreshold: TypedContractMethod<[], [bigint], "view">;

  kinetic: TypedContractMethod<[], [string], "view">;

  kineticMockAPY: TypedContractMethod<[], [bigint], "view">;

  morpho: TypedContractMethod<[], [string], "view">;

  morphoMarketParams: TypedContractMethod<
    [],
    [
      [string, string, string, string, bigint] & {
        loanToken: string;
        collateralToken: string;
        oracle: string;
        irm: string;
        lltv: bigint;
      }
    ],
    "view"
  >;

  morphoMockAPY: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  rebalance: TypedContractMethod<[], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputationHistory: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        timestamp: bigint;
        score: bigint;
        tier: bigint;
      }
    ],
    "view"
  >;

  setMockAPY: TypedContractMethod<
    [venue: BigNumberish, newAPY: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMorphoMarketParams: TypedContractMethod<
    [params: IMorpho.MarketParamsStruct],
    [void],
    "nonpayable"
  >;

  setThresholds: TypedContractMethod<
    [
      newBronzeThreshold: BigNumberish,
      newSilverThreshold: BigNumberish,
      newGoldThreshold: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  silverThreshold: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userUsingMorpho: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  userVenue: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bronzeThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositToVenue"
  ): TypedContractMethod<
    [amount: BigNumberish, venue: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposits"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[bigint, bigint] & { amount: bigint; timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "fxrp"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getBestVenue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentAPY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReputationHistory"
  ): TypedContractMethod<
    [user: AddressLike],
    [YieldRouter.ReputationSnapshotStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReputationTier"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "goldThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "kinetic"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "kineticMockAPY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "morpho"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "morphoMarketParams"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string, bigint] & {
        loanToken: string;
        collateralToken: string;
        oracle: string;
        irm: string;
        lltv: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "morphoMockAPY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rebalance"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputationHistory"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        timestamp: bigint;
        score: bigint;
        tier: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setMockAPY"
  ): TypedContractMethod<
    [venue: BigNumberish, newAPY: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMorphoMarketParams"
  ): TypedContractMethod<
    [params: IMorpho.MarketParamsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setThresholds"
  ): TypedContractMethod<
    [
      newBronzeThreshold: BigNumberish,
      newSilverThreshold: BigNumberish,
      newGoldThreshold: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "silverThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userUsingMorpho"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "userVenue"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "MockAPYUpdated"
  ): TypedContractEvent<
    MockAPYUpdatedEvent.InputTuple,
    MockAPYUpdatedEvent.OutputTuple,
    MockAPYUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MorphoMarketParamsUpdated"
  ): TypedContractEvent<
    MorphoMarketParamsUpdatedEvent.InputTuple,
    MorphoMarketParamsUpdatedEvent.OutputTuple,
    MorphoMarketParamsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Rebalanced"
  ): TypedContractEvent<
    RebalancedEvent.InputTuple,
    RebalancedEvent.OutputTuple,
    RebalancedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationSnapshotUpdated"
  ): TypedContractEvent<
    ReputationSnapshotUpdatedEvent.InputTuple,
    ReputationSnapshotUpdatedEvent.OutputTuple,
    ReputationSnapshotUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoutingUpdated"
  ): TypedContractEvent<
    RoutingUpdatedEvent.InputTuple,
    RoutingUpdatedEvent.OutputTuple,
    RoutingUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdsUpdated"
  ): TypedContractEvent<
    ThresholdsUpdatedEvent.InputTuple,
    ThresholdsUpdatedEvent.OutputTuple,
    ThresholdsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UserRoutingUpdated"
  ): TypedContractEvent<
    UserRoutingUpdatedEvent.InputTuple,
    UserRoutingUpdatedEvent.OutputTuple,
    UserRoutingUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Deposited(address,uint256,uint256,uint8)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "MockAPYUpdated(uint8,uint256)": TypedContractEvent<
      MockAPYUpdatedEvent.InputTuple,
      MockAPYUpdatedEvent.OutputTuple,
      MockAPYUpdatedEvent.OutputObject
    >;
    MockAPYUpdated: TypedContractEvent<
      MockAPYUpdatedEvent.InputTuple,
      MockAPYUpdatedEvent.OutputTuple,
      MockAPYUpdatedEvent.OutputObject
    >;

    "MorphoMarketParamsUpdated(address,address,address,address,uint256)": TypedContractEvent<
      MorphoMarketParamsUpdatedEvent.InputTuple,
      MorphoMarketParamsUpdatedEvent.OutputTuple,
      MorphoMarketParamsUpdatedEvent.OutputObject
    >;
    MorphoMarketParamsUpdated: TypedContractEvent<
      MorphoMarketParamsUpdatedEvent.InputTuple,
      MorphoMarketParamsUpdatedEvent.OutputTuple,
      MorphoMarketParamsUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Rebalanced(address,uint256,uint8,uint8)": TypedContractEvent<
      RebalancedEvent.InputTuple,
      RebalancedEvent.OutputTuple,
      RebalancedEvent.OutputObject
    >;
    Rebalanced: TypedContractEvent<
      RebalancedEvent.InputTuple,
      RebalancedEvent.OutputTuple,
      RebalancedEvent.OutputObject
    >;

    "ReputationSnapshotUpdated(address,uint256,uint256,uint8)": TypedContractEvent<
      ReputationSnapshotUpdatedEvent.InputTuple,
      ReputationSnapshotUpdatedEvent.OutputTuple,
      ReputationSnapshotUpdatedEvent.OutputObject
    >;
    ReputationSnapshotUpdated: TypedContractEvent<
      ReputationSnapshotUpdatedEvent.InputTuple,
      ReputationSnapshotUpdatedEvent.OutputTuple,
      ReputationSnapshotUpdatedEvent.OutputObject
    >;

    "RoutingUpdated(address,bool)": TypedContractEvent<
      RoutingUpdatedEvent.InputTuple,
      RoutingUpdatedEvent.OutputTuple,
      RoutingUpdatedEvent.OutputObject
    >;
    RoutingUpdated: TypedContractEvent<
      RoutingUpdatedEvent.InputTuple,
      RoutingUpdatedEvent.OutputTuple,
      RoutingUpdatedEvent.OutputObject
    >;

    "ThresholdsUpdated(uint256,uint256,uint256)": TypedContractEvent<
      ThresholdsUpdatedEvent.InputTuple,
      ThresholdsUpdatedEvent.OutputTuple,
      ThresholdsUpdatedEvent.OutputObject
    >;
    ThresholdsUpdated: TypedContractEvent<
      ThresholdsUpdatedEvent.InputTuple,
      ThresholdsUpdatedEvent.OutputTuple,
      ThresholdsUpdatedEvent.OutputObject
    >;

    "UserRoutingUpdated(address,uint8)": TypedContractEvent<
      UserRoutingUpdatedEvent.InputTuple,
      UserRoutingUpdatedEvent.OutputTuple,
      UserRoutingUpdatedEvent.OutputObject
    >;
    UserRoutingUpdated: TypedContractEvent<
      UserRoutingUpdatedEvent.InputTuple,
      UserRoutingUpdatedEvent.OutputTuple,
      UserRoutingUpdatedEvent.OutputObject
    >;

    "Withdrawn(address,uint256,uint256,uint8)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
