/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IYieldRouterForAttack,
  IYieldRouterForAttackInterface,
} from "../../../../contracts/mocks/MaliciousKinetic.sol/IYieldRouterForAttack";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IYieldRouterForAttack__factory {
  static readonly abi = _abi;
  static createInterface(): IYieldRouterForAttackInterface {
    return new Interface(_abi) as IYieldRouterForAttackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IYieldRouterForAttack {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IYieldRouterForAttack;
  }
}
