/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  MaliciousKinetic,
  MaliciousKineticInterface,
} from "../../../../contracts/mocks/MaliciousKinetic.sol/MaliciousKinetic";

const _abi = [
  {
    inputs: [],
    name: "attackOnMint",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "attackOnRedeem",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "exchangeRateStored",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "mintAmount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "redeemAmount",
        type: "uint256",
      },
    ],
    name: "redeemUnderlying",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "router",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "onMint",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "onRedeem",
        type: "bool",
      },
    ],
    name: "setAttackMode",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_router",
        type: "address",
      },
    ],
    name: "setRouter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "supplyRatePerBlock",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061035e806100206000396000f3fe608060405234801561001057600080fd5b506004361061009e5760003560e01c8063a0712d6811610066578063a0712d681461014f578063ae9d70b014610162578063c0d7865514610169578063ca6e349f14610199578063f887ea40146101ad57600080fd5b8063182df0f5146100a357806322cb36b1146100c057806370a08231146100e457806371371e08146100f8578063852a12e31461013c575b600080fd5b670de0b6b3a76400005b6040519081526020015b60405180910390f35b6000546100d490600160a81b900460ff1681565b60405190151581526020016100b7565b6100ad6100f2366004610297565b50600090565b61013a6101063660046102dc565b6000805461ffff60a01b1916600160a01b9315159390930260ff60a81b191692909217600160a81b91151591909102179055565b005b6100ad61014a36600461030f565b6101d8565b6100ad61015d36600461030f565b610253565b60006100ad565b61013a610177366004610297565b600080546001600160a01b0319166001600160a01b0392909216919091179055565b6000546100d490600160a01b900460ff1681565b6000546101c0906001600160a01b031681565b6040516001600160a01b0390911681526020016100b7565b60008054600160a81b900460ff161561024b57600054604051632e1a7d4d60e01b8152600481018490526001600160a01b0390911690632e1a7d4d906024015b600060405180830381600087803b15801561023257600080fd5b505af1158015610246573d6000803e3d6000fd5b505050505b506000919050565b60008054600160a01b900460ff161561024b5760005460405163b6b55f2560e01b8152600481018490526001600160a01b039091169063b6b55f2590602401610218565b6000602082840312156102a957600080fd5b81356001600160a01b03811681146102c057600080fd5b9392505050565b803580151581146102d757600080fd5b919050565b600080604083850312156102ef57600080fd5b6102f8836102c7565b9150610306602084016102c7565b90509250929050565b60006020828403121561032157600080fd5b503591905056fea264697066735822122015cee7aab49ef39a6f1fdfd3690a8317591e29be148879aada7ca15c1456e93264736f6c63430008180033";

type MaliciousKineticConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MaliciousKineticConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MaliciousKinetic__factory extends ContractFactory {
  constructor(...args: MaliciousKineticConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MaliciousKinetic & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MaliciousKinetic__factory {
    return super.connect(runner) as MaliciousKinetic__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MaliciousKineticInterface {
    return new Interface(_abi) as MaliciousKineticInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MaliciousKinetic {
    return new Contract(address, _abi, runner) as unknown as MaliciousKinetic;
  }
}
