/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  MaliciousKinetic,
  MaliciousKineticInterface,
} from "../../../../contracts/mocks/MaliciousKinetic.sol/MaliciousKinetic";

const _abi = [
  {
    inputs: [],
    name: "attackOnMint",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "attackOnRedeem",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "exchangeRateStored",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "mintAmount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "redeemAmount",
        type: "uint256",
      },
    ],
    name: "redeemUnderlying",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "router",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "onMint",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "onRedeem",
        type: "bool",
      },
    ],
    name: "setAttackMode",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_router",
        type: "address",
      },
    ],
    name: "setRouter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "supplyRatePerBlock",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f80fd5b506103418061001d5f395ff3fe608060405234801561000f575f80fd5b506004361061009b575f3560e01c8063a0712d6811610063578063a0712d6814610148578063ae9d70b01461015b578063c0d7865514610161578063ca6e349f14610190578063f887ea40146101a3575f80fd5b8063182df0f51461009f57806322cb36b1146100bc57806370a08231146100df57806371371e08146100f2578063852a12e314610135575b5f80fd5b670de0b6b3a76400005b6040519081526020015b60405180910390f35b5f546100cf90600160a81b900460ff1681565b60405190151581526020016100b3565b6100a96100ed366004610282565b505f90565b6101336101003660046102c3565b5f805461ffff60a01b1916600160a01b9315159390930260ff60a81b191692909217600160a81b91151591909102179055565b005b6100a96101433660046102f4565b6101cd565b6100a96101563660046102f4565b610240565b5f6100a9565b61013361016f366004610282565b5f80546001600160a01b0319166001600160a01b0392909216919091179055565b5f546100cf90600160a01b900460ff1681565b5f546101b5906001600160a01b031681565b6040516001600160a01b0390911681526020016100b3565b5f8054600160a81b900460ff1615610239575f54604051632e1a7d4d60e01b8152600481018490526001600160a01b0390911690632e1a7d4d906024015b5f604051808303815f87803b158015610222575f80fd5b505af1158015610234573d5f803e3d5ffd5b505050505b505f919050565b5f8054600160a01b900460ff1615610239575f5460405163b6b55f2560e01b8152600481018490526001600160a01b039091169063b6b55f259060240161020b565b5f60208284031215610292575f80fd5b81356001600160a01b03811681146102a8575f80fd5b9392505050565b803580151581146102be575f80fd5b919050565b5f80604083850312156102d4575f80fd5b6102dd836102af565b91506102eb602084016102af565b90509250929050565b5f60208284031215610304575f80fd5b503591905056fea2646970667358221220197a53c5035cdb020e77e11d730fe8aaec2780938ea1b994d366c7fa0fcff44364736f6c63430008180033";

type MaliciousKineticConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MaliciousKineticConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MaliciousKinetic__factory extends ContractFactory {
  constructor(...args: MaliciousKineticConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MaliciousKinetic & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MaliciousKinetic__factory {
    return super.connect(runner) as MaliciousKinetic__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MaliciousKineticInterface {
    return new Interface(_abi) as MaliciousKineticInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MaliciousKinetic {
    return new Contract(address, _abi, runner) as unknown as MaliciousKinetic;
  }
}
