/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as maliciousKineticSol from "./MaliciousKinetic.sol";
export type { maliciousKineticSol };
export type { MockFXRP } from "./MockFXRP";
export type { MockKinetic } from "./MockKinetic";
export type { MockMorpho } from "./MockMorpho";
