/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IMorpho {
  export type MarketStruct = {
    totalSupplyAssets: BigNumberish;
    totalSupplyShares: BigNumberish;
    totalBorrowAssets: BigNumberish;
    totalBorrowShares: BigNumberish;
    lastUpdate: BigNumberish;
    fee: BigNumberish;
  };

  export type MarketStructOutput = [
    totalSupplyAssets: bigint,
    totalSupplyShares: bigint,
    totalBorrowAssets: bigint,
    totalBorrowShares: bigint,
    lastUpdate: bigint,
    fee: bigint
  ] & {
    totalSupplyAssets: bigint;
    totalSupplyShares: bigint;
    totalBorrowAssets: bigint;
    totalBorrowShares: bigint;
    lastUpdate: bigint;
    fee: bigint;
  };

  export type MarketParamsStruct = {
    loanToken: AddressLike;
    collateralToken: AddressLike;
    oracle: AddressLike;
    irm: AddressLike;
    lltv: BigNumberish;
  };

  export type MarketParamsStructOutput = [
    loanToken: string,
    collateralToken: string,
    oracle: string,
    irm: string,
    lltv: bigint
  ] & {
    loanToken: string;
    collateralToken: string;
    oracle: string;
    irm: string;
    lltv: bigint;
  };
}

export interface MockMorphoInterface extends Interface {
  getFunction(
    nameOrSignature: "fxrpToken" | "market" | "supplied" | "supply" | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "fxrpToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "market", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "supplied",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supply",
    values: [
      IMorpho.MarketParamsStruct,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [
      IMorpho.MarketParamsStruct,
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike
    ]
  ): string;

  decodeFunctionResult(functionFragment: "fxrpToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "market", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "supplied", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "supply", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export interface MockMorpho extends BaseContract {
  connect(runner?: ContractRunner | null): MockMorpho;
  waitForDeployment(): Promise<this>;

  interface: MockMorphoInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  fxrpToken: TypedContractMethod<[], [string], "view">;

  market: TypedContractMethod<
    [arg0: BytesLike],
    [IMorpho.MarketStructOutput],
    "view"
  >;

  supplied: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  supply: TypedContractMethod<
    [
      arg0: IMorpho.MarketParamsStruct,
      assets: BigNumberish,
      arg2: BigNumberish,
      onBehalf: AddressLike,
      arg4: BytesLike
    ],
    [[bigint, bigint] & { assetsSupplied: bigint; sharesSupplied: bigint }],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [
      arg0: IMorpho.MarketParamsStruct,
      assets: BigNumberish,
      arg2: BigNumberish,
      onBehalf: AddressLike,
      receiver: AddressLike
    ],
    [[bigint, bigint] & { assetsWithdrawn: bigint; sharesWithdrawn: bigint }],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "fxrpToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "market"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [IMorpho.MarketStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "supplied"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "supply"
  ): TypedContractMethod<
    [
      arg0: IMorpho.MarketParamsStruct,
      assets: BigNumberish,
      arg2: BigNumberish,
      onBehalf: AddressLike,
      arg4: BytesLike
    ],
    [[bigint, bigint] & { assetsSupplied: bigint; sharesSupplied: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [
      arg0: IMorpho.MarketParamsStruct,
      assets: BigNumberish,
      arg2: BigNumberish,
      onBehalf: AddressLike,
      receiver: AddressLike
    ],
    [[bigint, bigint] & { assetsWithdrawn: bigint; sharesWithdrawn: bigint }],
    "nonpayable"
  >;

  filters: {};
}
