/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IKinetic__factory } from "./IKinetic__factory";
export { IMorpho__factory } from "./IMorpho__factory";
